
var_1: &cache_key mosaic-cache-{{ checksum "package.json" }}

anchor_job_defaults: &job_defaults
  working_directory: ~/mosaic
  docker:
    - image: ptsecurity/node-container:0.0.4

version: 2
jobs:

  build:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: System information
          command: |
            echo "Node.js $(node -v)"
            echo "npm $(npm -v)"
            echo "Yarn v$(yarn --version)"
      - run: npm install
      - save_cache:
          key: *cache_key
          paths:
            - node_modules
      - run: npm run mosaic:build-release

  test:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: System information
          command: |
            echo "Node.js $(node -v)"
            echo "npm $(npm -v)"
            echo "Yarn v$(yarn --version)"
      - run: npm install
      - save_cache:
          key: *cache_key
          paths:
            - node_modules
      - run: npm run test:unit
      - run: ./node_modules/.bin/codecov

  deploy:
    <<: *job_defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c3:de:eb:9c:82:70:a8:23:f3:4e:92:b8:07:d2:22:df"
      - checkout
      - restore_cache:
          key: *cache_key
      - run: npm install
      - run: npm run mosaic:build-release
      - run: npm run cdk:build-release
      - run: ./scripts/deploy/publish-artifacts.sh


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test
      - deploy:
          filters:
             branches:
               only:
                 - master
